# 排序节点的组织定义
OrdererOrgs:
  - Name: COWUNION # 名称
    Domain: cowunion.com # 域名
    Specs: # 节点域名：orderer.cowunion.com
      - Hostname: orderer # 主机名

# peer节点的组织定义
PeerOrgs:
  # EN1-组织
  - Name: EN1 # 名称
    Domain: enterprise1.com # 域名
    Template: # 使用模板定义。Count 指的是该组织下组织节点的个数
      Count: 2 # 节点域名：peer0.enterprise1.com 和 peer1.enterprise1.com
    Users: # 组织的用户信息。Count 指该组织中除了 Admin 之外的用户的个数
      Count: 1 # 用户：Admin 和 User1

  # EN2-组织
  - Name: EN2
    Domain: enterprise2.com
    Template:
      Count: 2 # 节点域名：peer0.enterprise2.com 和 peer1.enterprise2.com
    Users:
      Count: 1 # 用户：Admin 和 User1