version: '2.1'

volumes:
  orderer.cowunion.com:
  peer0.enterprise1.com:
  peer1.enterprise1.com:
  peer0.enterprise2.com:
  peer1.enterprise2.com:

networks:
  fabric_network:
    name: fabric_network

services:
  # 排序服务节点
  orderer.cowunion.com:
    container_name: orderer.cowunion.com
    image: hyperledger/fabric-orderer:1.4.12
    environment:
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block # 注入创世区块
      - ORDERER_GENERAL_LOCALMSPID=COWUNIONMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp # 证书相关
    command: orderer
    ports:
      - "7050:7050"
    volumes: # 挂载由cryptogen和configtxgen生成的证书文件以及创世区块
      - ./config/genesis.block:/etc/hyperledger/config/genesis.block
      - ./crypto-config/ordererOrganizations/cowunion.com/orderers/orderer.cowunion.com/:/etc/hyperledger/orderer
      - orderer.cowunion.com:/var/hyperledger/production/orderer
    networks:
      - fabric_network

  #  EN1 组织 peer0 节点
  peer0.enterprise1.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.enterprise1.com
    environment:
      - CORE_PEER_ID=peer0.enterprise1.com
      - CORE_PEER_LOCALMSPID=EN1MSP
      - CORE_PEER_ADDRESS=peer0.enterprise1.com:7051
    ports:
      - "7051:7051" # grpc服务端口
      - "7053:7053" # eventhub端口
    volumes:
      - ./crypto-config/peerOrganizations/enterprise1.com/peers/peer0.enterprise1.com:/etc/hyperledger/peer
      - peer0.enterprise1.com:/var/hyperledger/production
    depends_on:
      - orderer.cowunion.com

  #  EN1 组织 peer1 节点
  peer1.enterprise1.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.enterprise1.com
    environment:
      - CORE_PEER_ID=peer1.enterprise1.com
      - CORE_PEER_LOCALMSPID=EN1MSP
      - CORE_PEER_ADDRESS=peer1.enterprise1.com:7051
    ports:
      - "17051:7051"
      - "17053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/enterprise1.com/peers/peer1.enterprise1.com:/etc/hyperledger/peer
      - peer1.enterprise1.com:/var/hyperledger/production
    depends_on:
      - orderer.cowunion.com

  #  EN2 组织 peer0 节点
  peer0.enterprise2.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.enterprise2.com
    environment:
      - CORE_PEER_ID=peer0.enterprise2.com
      - CORE_PEER_LOCALMSPID=EN2MSP
      - CORE_PEER_ADDRESS=peer0.enterprise2.com:7051
    ports:
      - "27051:7051"
      - "27053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/enterprise2.com/peers/peer0.enterprise2.com:/etc/hyperledger/peer
      - peer0.enterprise2.com:/var/hyperledger/production
    depends_on:
      - orderer.cowunion.com

  #  EN2 组织 peer1 节点
  peer1.enterprise2.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.enterprise2.com
    environment:
      - CORE_PEER_ID=peer1.enterprise2.com
      - CORE_PEER_LOCALMSPID=EN2MSP
      - CORE_PEER_ADDRESS=peer1.enterprise2.com:7051
    ports:
      - "37051:7051"
      - "37053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/enterprise2.com/peers/peer1.enterprise2.com:/etc/hyperledger/peer
      - peer1.enterprise2.com:/var/hyperledger/production
    depends_on:
      - orderer.cowunion.com

  # 客户端节点
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.12
    tty: true
    environment:
      # go 环境设置
      - GO111MODULE=auto
      - GOPROXY=https://goproxy.cn
      - CORE_PEER_ID=cli
    command: /bin/bash
    volumes:
      - ./config:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/enterprise1.com/:/etc/hyperledger/peer/enterprise1.com
      - ./crypto-config/peerOrganizations/enterprise2.com/:/etc/hyperledger/peer/enterprise2.com
      - ./../chaincode:/opt/gopath/src/chaincode # 链码路径注入
    networks:
      - fabric_network
    depends_on:
      - orderer.cowunion.com
      - peer0.enterprise1.com
      - peer1.enterprise1.com
      - peer0.enterprise2.com
      - peer1.enterprise2.com